project_id = "exybvjqjdqxonhesydhk"

[functions.stripe-webhook]
verify_jwt = false

[functions.liff-auth]
verify_jwt = false

[functions.make-webhook]
verify_jwt = false

[functions.auth-register]
verify_jwt = false